import type { Metadata } from 'next';
import './globals.css';
import Header from '@/features/ui/layout/Header';

export const metadata: Metadata = {
  title: 'nuko.brand',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="uk">
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
